name: Build and deploy .NET application to container app cawhittakerapi-app-2024090515225
on:
  push:
    branches:
    - main
env:
  CONTAINER_APP_CONTAINER_NAME: cawhittakerapi
  CONTAINER_APP_NAME: cawhittakerapi-app-2024090515225
  CONTAINER_APP_RESOURCE_GROUP_NAME: ca-testing
  CONTAINER_REGISTRY_LOGIN_SERVER: cawhittakerapi20240905151221.azurecr.io
  DOTNET_CORE_VERSION: 9.0.x
  PROJECT_NAME_FOR_DOCKER: cawhittakerapi-app-2024090515225
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-quality: preview
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Log in to container registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.cawhittakerapi20240905151221_USERNAME_121C }}
        password: ${{ secrets.cawhittakerapi20240905151221_PASSWORD_121C }}
    - name: Build and push container image to registry
      run: dotnet publish -c Release -r linux-x64 -p:PublishProfile=DefaultContainer -p:ContainerImageTag=${{ github.sha }} --no-self-contained -p:ContainerRegistry=${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} -bl
    - name: Upload binlog for investigation
      uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        name: binlog
        path: msbuild.binlog
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.cawhittakerapi_app_2024090515225_SPN }}
    - name: Deploy to containerapp
      uses: azure/CLI@v2
      with:
        inlineScript: >
          az config set extension.use_dynamic_install=yes_without_prompt

          az containerapp registry set --name ${{ env.CONTAINER_APP_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --server ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }} --username ${{ secrets.cawhittakerapi20240905151221_USERNAME_121C }} --password ${{ secrets.cawhittakerapi20240905151221_PASSWORD_121C }}

          az containerapp update --name ${{ env.CONTAINER_APP_NAME }} --container-name ${{ env.CONTAINER_APP_CONTAINER_NAME }} --resource-group ${{ env.CONTAINER_APP_RESOURCE_GROUP_NAME }} --image ${{ env.CONTAINER_REGISTRY_LOGIN_SERVER }}/${{ env.PROJECT_NAME_FOR_DOCKER }}:${{ github.sha }}
    - name: logout
      run: >
        az logout
